arsip/app/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    #root user
    path('super/', rootSuper),
    path('super/homepage/', rootHomepage, name='super-homepage'),
    path('super/homepage/department/', rootDepartment),
    path('super/homepage/suratmasuk/', rootSuratmasuk),
    path('super/homepage/suratkeluar/', rootSuratkeluar),
    path('super/homepage/department/<str:divisi>', rootDivisi),
    path('super/users/', rootUser, name='super_user'),


    ## general purpose
    path('login/', login),
    path('homepage/', homepage, name='homepage'),
    # url surat masuk   
    path('homepage/suratmasuk/', suratmasuk, name='suratmasuk'),
    path('homepage/suratmasuk/<str:filename>', suratmasukdetail, name='suratmasukdetail'),
    # url surat keluar
    path('homepage/suratkeluar/', suratkeluar, name='suratkeluar'),
    path('homepage/suratkeluar/<str:filename>', suratkeluardetail, name='suratkeluardetail'),
    path('approve/<str:file>', approve),
    path('logout/', logout, name='logout')
]

arsip/arsip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # ALL FILE ON DATABASE!

arsip/app/models.py
from django.db import models
from django.utils import timezone

# Tabel Departemen
class Department(models.Model):
    departementID = models.CharField(max_length=6, null=False)
    departementName = models.CharField(max_length=21, null=False)
    created_at = models.DateTimeField(default=timezone.now)
    url = models.CharField(null=True, max_length=40)
    status = models.BooleanField(default=True)    
    
    def __str__(self):
        return self.departementName

# Tabel Divisi
class Divisi(models.Model):
    divisiID = models.CharField(max_length=6, null=False)
    divisiName = models.CharField(max_length=21, null=False)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    url = models.CharField(null=True, max_length=40)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        department = str(self.department)
        return (f'{self.divisiName} - {department}')

# Tabel Role Karyawan (Staff, Manajer, dll)
class Role(models.Model):
    roleCode = models.CharField(max_length=4, null=False)
    roleName = models.CharField(max_length=16, null=False)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.roleName

# Tabel Jenis Berkas (Dinas, Selebaran, dll)
class JenisBerkas(models.Model):
    jenisCode = models.CharField(max_length=6)
    jenisName = models.CharField(max_length=16)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.jenisName

# Tabel Pengguna
class Pengguna(models.Model):
    username = models.CharField(max_length=21, null=False)
    password = models.TextField(max_length=21, null=False)
    firstName = models.CharField(max_length=14, null=False)
    lastName = models.CharField(max_length=14, null=False)
    nik = models.TextField(max_length=60, blank=True)
    qr_code = models.IntegerField(null=False)
    time_login = models.IntegerField(default=5000)
    cookies    = models.TextField(max_length=21, blank=True)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, null=True)
    department = models.ManyToManyField(Department)
    divisi = models.ManyToManyField(Divisi, blank=True)
    status = models.BooleanField(default=True)

    def __str__(self):
        return (f'{self.firstName} {self.lastName}')

    def get_department(self):
        if (self.department.count()==1):
            return self.department.all()[0]
        else:
            return self.department.all()[0]

# Table file
class File(models.Model):
    fileName = models.CharField(max_length=120)
    file = models.FileField(upload_to='', null=False)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.fileName

# Tabel Berkas Masuk
class SuratMasuk(models.Model):
    TYPE_BERKAS = [('B', 'Biasa'), ('P', 'Penting'), ('SP', 'Sangat Penting')]
    file = models.ManyToManyField(File)
    fileName = models.CharField(max_length=40, default=file.name)
    jenisBerkas = models.ForeignKey(JenisBerkas, on_delete=models.CASCADE)
    typeBerkas = models.CharField(choices=TYPE_BERKAS, max_length=10, default='B')
    # general purpose
    department = models.ManyToManyField(Department)
    upload_for = models.ManyToManyField(Pengguna, related_name='target')
    address_sender = models.CharField(max_length=160, null=True)
    sender = models.CharField(max_length=120, null=True)
    perihal = models.CharField(max_length=60)
    nomor_surat = models.CharField(max_length=60)
    created_at = models.DateTimeField(default=timezone.now)
    url = models.CharField(null=True, max_length=40)
    ## Berkas workflow
    reader = models.ManyToManyField(Pengguna, related_name='reader', blank=True)
    approve_by = models.ManyToManyField(Pengguna, related_name='approved', blank=True)
    # status active/inactive file
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.fileName

# Tabel Berkas Masuk
class SuratKeluar(models.Model):
    TYPE_BERKAS = [('B', 'Biasa'), ('P', 'Penting'), ('SP', 'Sangat Penting')]
    file = models.ManyToManyField(File)
    fileName = models.CharField(max_length=120, default=file.name)
    jenisBerkas = models.ForeignKey(JenisBerkas, on_delete=models.CASCADE)
    typeBerkas = models.CharField(choices=TYPE_BERKAS, max_length=16,default='B')
    # general purpose
    department = models.ManyToManyField(Department)
    destination = models.CharField(max_length=160, null=True)
    destination_address = models.CharField(max_length=160, null=True)
    perihal = models.CharField(max_length=60)
    nomor_surat = models.CharField(max_length=60, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    url = models.CharField(null=True, max_length=40)

    def __str__(self):
        return self.fileName

# Semua berkas yang sudah selesai
class Arsip(models.Model):
    TYPE_BERKAS = [('B', 'Biasa'), ('P', 'Penting'), ('SP', 'Sangat Penting')]
    TYPE_GROUP = [('SM', 'Surat Masuk'), ('SK', 'Surat Keluar')]
    fileName = models.CharField(max_length=120)
    file_path = models.ManyToManyField(File)
    perihal = models.CharField(max_length=60)
    nomor_surat = models.CharField(max_length=60, null=True)
    typeBerkas = models.CharField(choices=TYPE_BERKAS, max_length=16,default='B')
    group = models.CharField(choices=TYPE_GROUP, max_length=16,default='SM')

arsip/app/templates/base.html
<!doctype html>
<html lang="en">
    <head>
        {%load static%}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

          <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'bootstrap/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/components.css' %}">
        
        <title>Management</title>
    </head>
  <body>
          
            {% block content %}

            {% endblock %}
        
        
  </body>
</html>

arsip/app/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div id="app">
  <section class="section">
    <div class="container mt-5">
      <div class="row">
        <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">


          <div class="card card-primary">
            <div class="card-header"><h4>Login</h4></div>

            <div class="card-body">
              <form method="POST" action="" class="needs-validation" novalidate="">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username">Username</label>
                  <input id="username" type="text" class="form-control" name="namapengguna" tabindex="1" required autofocus>
                  <div class="invalid-feedback">
                    Silahkan isi email anda!
                  </div>
                </div>

                <div class="form-group">
                  <div class="d-block">
                    <label for="password" class="control-label">Password</label>
                  </div>
                  <input id="password" type="password" class="form-control" name="katasandi" tabindex="2" required>
                  <div class="invalid-feedback">
                    Silahkan isi password anda!
                  </div>
                </div>

                <div class="form-group text-center">
                  <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                    Masuk
                  </button>
                </div>
              </form>
            </div>
          </div>

          <div class="simple-footer">
            <div class="mt-1 text-muted text-center">
              Silahkan hubungi administrator untuk daftar akun.
            </div>
            Copyright &copy; Kearsipan 2021
          </div>
        </div>
      </div>
    </div>
  </section>
</div>


<!-- General JS Scripts -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  {%load static%}
  <script src="{% static 'bootstrap/js/stisla.js' %}"></script>

  <!-- JS Libraies -->

  <!-- Template JS File -->
  <script src="{% static 'bootstrap/js/scripts.js' %}"></script>
  <script src="{% static 'bootstrap/js/custom.js' %}"></script>
{% endblock %}

arsip/app/templates/suratkeluar.html
<!doctype html>
<html lang="en">
    <head>
        {%load static%}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

          <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'bootstrap/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/styledivisi.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/components.css' %}">
        
        <title>Management</title>
    </head>
  <body>

{% block content %}
<div id="app">
  <div class="main-wrapper">
    <!-- NAVBAR -->
    <div class="navbar-bg"></div>
    <nav class="navbar navbar-expand-lg main-navbar" style="justify-content: flex-end;">
      <a href="/homepage/" class="h4 mr-auto text-white" style="text-decoration: none;padding-left: 16px;">Company</a>
      
      <!-- Notif & profile -->
      <ul class="navbar-nav navbar-right">
        {% if notifications_list.count != 0 %}
        
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
          <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Pemberitahuan</div>
            <div class="dropdown-list-content dropdown-list-icons">
 
              {% for i in notifications_list %}
              <a href="/homepage/suratmasuk/{{i.url}}" class="dropdown-item">
                <div class="dropdown-item-icon bg-info text-white">
                  <i class="fas fa-bell"></i>
                </div>
                <div class="dropdown-item-desc">
                    {{i.fileName}}
                  <div class="time">{{ i.created_at }}</div>
                </div>
              </a>
              {% endfor %}


            </div>
          </div>
        
          {% else %}

          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Pemberitahuan</div>
              <div class="dropdown-list-content dropdown-list-icons">
   
                {% for i in notifications_list %}
                <a href="/homepage/suratmasuk/{{i.url}}" class="dropdown-item">
                  <div class="dropdown-item-icon bg-info text-white">
                    <i class="fas fa-bell"></i>
                  </div>
                  <div class="dropdown-item-desc">
                      {{i.fileName}}
                    <div class="time">{{ i.created_at }}</div>
                  </div>
                </a>
                {% endfor %}
            
              </div>
            </div>
          {% endif %}
        
          
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          <div class="d-sm-none d-lg-inline-block" style="font-size: 20px;">{{ user.firstName }} {{ user.lastName }}</div>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="/homepage/suratmasuk" class="dropdown-item has-icon">
              Surat Masuk
            </a>
            <a href="/homepage/suratkeluar" class="dropdown-item has-icon">
              Surat Keluar
            </a>
            <a href="" class="dropdown-item has-icon">
              Pengaturan Akun
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item has-icon text-danger">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </div>
        </li>
      </ul>
      <!-- NAVBAR -->

    </nav>
      <div class="main-content" style="padding-left: 30px">
      <section class="section">
        <div class="section-header">
          <h1>Dashboard</h1>
        </div>
        <div class="row">

          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <div class="section-title mt-0">Surat Keluar</div>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Nama File</th>
                      <th scope="col">Nomor Surat</th>
                      <th scope="col">Perihal</th>
                      <th scope="col">Penerima</th>
                      <th scope="col">Jenis Berkas</th>
                      <th scope="col">Tipe Berkas</th>
                      <th scope="col">Tanggal dibuat</th>
                      <th scope="col"></th>
                      <br>
                    </tr>
                  </thead>
                  <tbody>
                  
                    {% for i in sk_list %}
                    
                    {% if i.typeBerkas == 'SP' %}
                    <tr class="bg-danger text-white">
                      <td>{{ i.fileName }}</td>
                      <td>{{ i.nomor_surat}} </td>
                      <td>{{ i.perihal }}</td>
                      <td>{{ i.destination }}</td>
                      <td>{{ i.jenisBerkas }} </td>
                      <td> {{ i.get_typeBerkas_display }} </td>
                      <td> {{ i.created_at }} </td>
                      <td><a href="{{i.url}}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                    </tr>
                    {% else %}
                    
                    <tr>
                        <td>{{ i.fileName }}</td>
                        <td>{{ i.nomor_surat}} </td>
                        <td>{{ i.perihal }}</td>
                        <td>{{ i.destination }}</td>
                        <td>{{ i.jenisBerkas }} </td>
                        <td> {{ i.get_typeBerkas_display }} </td>
                        <td> {{ i.created_at }} </td>
                      <td><a href="{{i.url}}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        </div>
        </section>

        <script>
          setTimeout(function(){
             window.location.href = '';
          }, 100000);
       </script>

<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
{%load static%}
<script src="{% static 'bootstrap/js/stisla.js' %}"></script>

<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{% static 'bootstrap/js/scripts.js' %}"></script>
<script src="{% static 'bootstrap/js/custom.js' %}"></script>
<script src="{% static 'bootstrap/js/index.js' %}"></script>



{% endblock %}

arsip/app/templates/suratmasuk.html
<!doctype html>
<html lang="en">
    <head>
        {%load static%}
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

          <!-- General CSS Files -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
        
        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'bootstrap/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/styledivisi.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap/css/components.css' %}">
        
        <title>Management</title>
    </head>
  <body>
{% block content %}
<div id="app">
  <div class="main-wrapper">
    <!-- NAVBAR -->
    <div class="navbar-bg"></div>
    <nav class="navbar navbar-expand-lg main-navbar">
      <a href="/homepage/" class="h4 mr-auto text-white" style="text-decoration: none;padding-left: 16px;">Company</a>
      

      <!-- Notif & profile -->
      <ul class="navbar-nav navbar-right">
        {% if notifications_list.count != 0 %}
        
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
          <div class="dropdown-menu dropdown-list dropdown-menu-right">
            <div class="dropdown-header">Pemberitahuan</div>
            <div class="dropdown-list-content dropdown-list-icons">
 
              {% for i in notifications_list %}
              <a href="/homepage/suratmasuk/{{i.url}}" class="dropdown-item">
                <div class="dropdown-item-icon bg-info text-white">
                  <i class="fas fa-bell"></i>
                </div>
                <div class="dropdown-item-desc">
                    {{i.fileName}}
                  <div class="time">{{ i.created_at }}</div>
                </div>
              </a>
              {% endfor %}


            </div>
          </div>
        
          {% else %}

          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Pemberitahuan</div>
              <div class="dropdown-list-content dropdown-list-icons">
   
                {% for i in notifications_list %}
                <a href="/homepage/suratmasuk/{{i.url}}" class="dropdown-item">
                  <div class="dropdown-item-icon bg-info text-white">
                    <i class="fas fa-bell"></i>
                  </div>
                  <div class="dropdown-item-desc">
                      {{i.fileName}}
                    <div class="time">{{ i.created_at }}</div>
                  </div>
                </a>
                {% endfor %}
            
              </div>
            </div>
          {% endif %}
        
          
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
          <div class="d-sm-none d-lg-inline-block" style="font-size: 20px;">{{ user.firstName }} {{ user.lastName }}</div>
          <div class="dropdown-menu dropdown-menu-right">
            <a href="/homepage/suratmasuk" class="dropdown-item has-icon">
              Surat Masuk
            </a>
            <a href="/homepage/suratkeluar" class="dropdown-item has-icon">
              Surat Keluar
            </a>
            <a href="" class="dropdown-item has-icon">
              Pengaturan Akun
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item has-icon text-danger">
              <i class="fas fa-sign-out-alt"></i> Logout
            </a>
          </div>
        </li>
      </ul>
      <!-- NAVBAR -->

    </nav>
      <div class="main-content" style="padding-left: 30px">
      <section class="section">
        <div class="section-header">
          <h1>Dashboard</h1>
        </div>
        <div class="row">

          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <div class="section-title mt-0">Surat Masuk</div>
                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">Nama File</th>
                      <th scope="col">Pengirim</th>
                      <th scope="col">Deskripsi</th>
                      <th scope="col">Jenis Berkas</th>
                      <th scope="col">Tipe Berkas</th>
                      <th scope="col"></th>
                      <br>
                    </tr>
                  </thead>
                  <tbody>
                  
                    {% for i in sm_list %}
                    
                    {% if i.typeBerkas == 'SP' %}
                    <tr class="bg-danger text-white">
                      <td>{{ i.fileName }}</td>
                      <td>{{ i.sender}} </td>
                      <td>{{ i.perihal }}</td>
                      <td>{{ i.jenisBerkas}} </td>
                      <td> {{ i.get_typeBerkas_display }} </td>
                      <td><a href="{{i.url}}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                    </tr>
                    {% else %}
                    
                    <tr>
                      <td>{{ i.fileName }}</a></td>
                      <td>{{ i.sender}} </td>
                      <td>{{ i.perihal }}</td>
                      <td>{{ i.jenisBerkas}} </td>
                      <td> {{ i.get_typeBerkas_display }} </td>
                      <td><a href="{{i.url}}" class="btn btn-primary"><i class="fa fa-eye"></i></a></td>
                    </tr>
                    {% endif %}
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>

        </div>
        </section>

        <script>
          setTimeout(function(){
             window.location.href = '';
          }, 100000);
       </script>

<!-- General JS Scripts -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
{%load static%}
<script src="{% static 'bootstrap/js/stisla.js' %}"></script>

<!-- JS Libraies -->

<!-- Template JS File -->
<script src="{% static 'bootstrap/js/scripts.js' %}"></script>
<script src="{% static 'bootstrap/js/custom.js' %}"></script>
<script src="{% static 'bootstrap/js/index.js' %}"></script>



{% endblock %}